import type { Metadata } from "next"
import { LegalPageLayout } from "@/components/legal/LegalPageLayout"

export const metadata: Metadata = {
  title: "AI & Editorial Methodology — Inbound Reports",
  description: "How Inbound Reports aggregates, processes, and presents tech news.",
}

export default function MethodologyPage() {
  return (
    <LegalPageLayout title="How We Operate">
      <p className="label-meta !normal-case tracking-normal mb-6">
        Last updated: July 29, 2026
      </p>

      <p>
        <strong>Transparency is core to our mission.</strong> This page documents exactly how Inbound
        Reports aggregates, processes, and presents news. Nothing here is aspirational — this
        describes the system as it currently functions.
      </p>

      <h2>1. Source Aggregation</h2>
      <p>
        We maintain a curated directory of <strong>900+ active</strong> technology news sources —
        including RSS feeds, APIs, developer communities, and regional publications — scaling daily.
        New sources are added by editing the YAML configuration; no code or database changes are
        required. Each source is manually vetted for relevance. Our ingestion workers fetch new
        content periodically, parse article metadata, and store them for processing.
      </p>

      <h2>2. Story Clustering</h2>
      <p>
        When multiple sources cover the same topic, our system groups related articles into a single
        &quot;Story Event.&quot; The cluster is formed by comparing headline and summary similarity
        across articles. Stories with a similarity score above a threshold are grouped together,
        and the cluster&apos;s source count reflects how many independent outlets are covering that
        story — a signal of importance.
      </p>

      <h2>3. AI Processing Stack</h2>
      <p>
        We use a multi-provider AI router with automatic fallback to ensure reliability while keeping
        the platform free. The chain is:
      </p>
      <div className="space-y-4 mt-3 mb-5">
        <div className="flex gap-3">
          <span className="font-mono text-[var(--accent)] shrink-0 mt-0.5">+</span>
          <div>
            <p className="font-semibold text-[var(--text-primary)]">Groq (primary): Llama 3.3 70B</p>
            <p className="text-[var(--text-secondary)] mt-1">Used for classification, tagging, and primary summarization.</p>
            <p className="text-[var(--text-secondary)]">Supports multiple API keys for round-robin load balancing.</p>
          </div>
        </div>
        <div className="flex gap-3">
          <span className="font-mono text-[var(--accent)] shrink-0 mt-0.5">+</span>
          <div>
            <p className="font-semibold text-[var(--text-primary)]">OpenRouter (fallback): multi-provider aggregator</p>
            <p className="text-[var(--text-secondary)] mt-1">Used when Groq is unavailable.</p>
            <p className="text-[var(--text-secondary)]">Default model: Llama 3.3 70B Instruct.</p>
          </div>
        </div>
        <div className="flex gap-3">
          <span className="font-mono text-[var(--accent)] shrink-0 mt-0.5">+</span>
          <div>
            <p className="font-semibold text-[var(--text-primary)]">Google Gemini (last resort): Gemini 2.0 Flash</p>
            <p className="text-[var(--text-secondary)] mt-1">Used when both Groq and OpenRouter are exhausted or rate-limited.</p>
          </div>
        </div>
      </div>
      <p>
        If all providers are unavailable, the system degrades gracefully by using pre-written
        fallback text rather than failing entirely.
      </p>

      <h2>4. The Hype-Reality Bar</h2>
      <p>
        Our signature visual is generated by analyzing the linguistic structure of news text. The AI
        evaluates each article for the density of marketing superlatives (e.g., &quot;revolutionary,&quot;
        &quot;game-changing,&quot; &quot;unprecedented&quot;) versus the presence of measured claims, data citations,
        and primary sources. The result is a score from 0 (pure substance) to 1 (pure hype).
        When multiple articles cover the same story, each source gets its own score, and an
        aggregate score is shown alongside individual source dots.
      </p>

      <h2>5. The Literacy Layer</h2>
      <p>
        <strong>Jargon Highlighting:</strong> Complex technical terms in article summaries are
        automatically matched against our glossary and highlighted in red. Tapping a highlighted
        term opens a popover with a plain-English definition and an analogy.
      </p>
      <p>
        <strong>ELI5 (Explain Like I&apos;m 5):</strong> A simplified reading tier that uses
        text processing — replacing complex vocabulary with simpler alternatives and removing
        parenthetical asides — to make technical news more accessible. This is a deterministic
        text simplification, not an AI rewrite.
      </p>
      <p>
        <strong>Khmer Language:</strong> The platform interface includes a Khmer language toggle
        in the header, and the glossary contains Khmer definitions for many terms. Full Khmer
        translations of stories are a planned feature and not yet implemented. The toggle currently
        preserves your language preference for when full support launches.
      </p>

      <h2>6. The &quot;Local Lens — Cambodia&quot; Feature</h2>
      <p>
        On each story page, a sidebar box attempts to generate a paragraph explaining why that story
        matters specifically to a Cambodian audience. This uses a lightweight AI model (Groq /
        Llama 3.1 8B) with a prompt focused on Cambodian relevance. The feature is best-effort:
        if the AI is unavailable, a fallback paragraph based on the story&apos;s category is shown
        instead.
      </p>

      <h2>7. Hype Predictions (Hype Retrospective)</h2>
      <p>
        Registered readers can vote on whether a technology or trend is &quot;Overhyped,&quot;
        &quot;Will deliver,&quot; or &quot;Too early to tell.&quot; These predictions are stored
        locally in your browser and are not currently synced across devices. This feature is
        experimental and used for personal reflection rather than aggregate data.
      </p>

      <h2>8. Updates to This Methodology</h2>
      <p>
        As our system evolves, this page will be updated to reflect changes. The &quot;Last
        updated&quot; date at the top of this page indicates when the methodology documentation
        was last reviewed.
      </p>
    </LegalPageLayout>
  )
}
