import type { Metadata } from "next"
import { LegalPageLayout } from "@/components/legal/LegalPageLayout"

export const metadata: Metadata = {
  title: "AI & Editorial Methodology — Inbound Reporter",
  description: "How Inbound Reporter aggregates, processes, and presents tech news using AI.",
}

export default function MethodologyPage() {
  return (
    <LegalPageLayout title="Our AI & Editorial Methodology">
      <p>
        <strong>Transparency is core to our mission of increasing digital literacy.</strong> Here is exactly
        how Inbound Reporter operates.
      </p>

      <h2>1. Source Aggregation</h2>
      <p>
        We pull from a dynamically scaling network of over 900 global and regional tech sources, including
        APIs, RSS feeds, and developer communities. We do not manually copy articles; our system fetches
        metadata and text to create a canonical &quot;Story Event.&quot;
      </p>

      <h2>2. AI Processing Stack</h2>
      <p>
        We do not use a single AI. To ensure uptime and quality while keeping the platform free, we use a
        multi-provider AI fallback router:
      </p>
      <ul>
        <li>
          <strong>Groq (Llama 3.3 70B &amp; 3.1 8B):</strong> Used for fast classification, tagging, and
          Khmer translation.
        </li>
        <li>
          <strong>DeepSeek V4 Flash:</strong> Used for high-quality English summarization and
          &quot;Hype-Reality&quot; reasoning.
        </li>
        <li>
          <strong>Google Gemini:</strong> Used for low-resource Khmer language tasks.
        </li>
        <li>
          <strong>Cache:</strong> We use a content-hash cache, meaning if an article has already been
          summarized, we serve the cached version instantly without spending additional AI compute.
        </li>
      </ul>

      <h2>3. The Hype-Reality Bar</h2>
      <p>
        Our signature visual is generated by AI analyzing the linguistic structure of the articles. We
        score sources based on the density of marketing superlatives (e.g., &quot;revolutionary,&quot;
        &quot;game-changing&quot;) versus the presence of primary source citations and measured claims.
      </p>

      <h2>4. The Literacy Layer (ELI5 &amp; Jargon)</h2>
      <p>
        Complex tech terms are automatically extracted by our AI and highlighted in red. Tapping them opens
        a bilingual glossary card. The &quot;ELI5&quot; (Explain Like I&apos;m 5) tier uses AI to rewrite technical
        news using simple, real-world analogies in spoken Khmer.
      </p>
    </LegalPageLayout>
  )
}
